Get version string correctly when repacking on Chrome OS images.
The 'version updating' procedure in repack relies on 'strings' utility, which is
not available on Chrome OS images.

To improve that and to avoid unexpected error messages, we should detect
available programs first, and use dump_vpd if available.

BUG=chrome-os-partner:30907
TEST=chromeos-firmwareupdate --repack /tmp/blah # on Chrome OS image.

Change-Id: I33d0bef1b913a5d728a694a3f054292868a7bda4
Reviewed-on: https://chromium-review.googlesource.com/210465
Tested-by: Hung-Te Lin <hungte@chromium.org>
Reviewed-by: Randall Spangler <rspangler@chromium.org>
Commit-Queue: Hung-Te Lin <hungte@chromium.org>

diff --git a/pack_stub b/pack_stub
--- a/pack_stub
+++ b/pack_stub
@@ -122,11 +122,32 @@ find_version_string() {
   if [ ! -s "$filename" ]; then
     return
   fi
-  local version="$( (strings "$filename" | grep "$pattern" | uniq) || echo "")"
-  if [ "$(echo "version" | wc -l)" -ne "1" ]; then
-    version=""
+
+  # Chrome OS & chroot has dump_fmap, and standard Linux desktop has strings.
+  if type dump_fmap >/dev/null 2>&1; then
+
+    local tmpdir="$(mktemp -d)"
+    local filepath="$(readlink -f "$filename")"
+    (cd "$tmpdir"; dump_fmap -x "$filepath") >/dev/null 2>&1
+    cat "$tmpdir/RO_FRID" 2>/dev/null
+    rm -rf "$tmpdir"
+
+  elif type strings >/dev/null 2>&1; then
+
+    local version="$( (strings "$filename" | grep "$pattern" | uniq) || true)"
+    if [ "$(echo "version" | wc -l)" -ne "1" ]; then
+      version=""
+    fi
+    echo "$version"
+
+  else
+
+    (echo "WARNING: 'strings' and 'dump_fmap' are both not available."
+     echo "         TARGET_{FW,EC}ID can't be updated."
+     echo "         You have to manually change that or repack on a desktop."
+     ) >&2
+
   fi
-  echo "$version"
 }
 
 # Repacks current file ($SELF) by given source folder.
