FW Updater: propogate return code in pack_stub
This is necessary, because the firmware updater returns 3 if the
machine booted from FW slot B, and this needs to get back to the
updater.

BUG=chromium-os:14343
TEST=on device test

Change-Id: I1021f27edf99ff29d870adabbc39cf9677a048d0
Reviewed-on: http://gerrit.chromium.org/gerrit/2218
Tested-by: Andrew de los Reyes <adlr@chromium.org>
Reviewed-by: Stefan Reinauer <reinauer@chromium.org>

diff --git a/pack_stub b/pack_stub
--- a/pack_stub
+++ b/pack_stub
@@ -181,8 +181,11 @@ if [ "$TARGET_PLATFORM" = "Mario" ]; then
 fi
 
 verbose_message "Run built-in script ($SCRIPT) ..."
-if ! $SCRIPT "$@"; then
-  error_exit "ERROR: $SCRIPT failed."
+$SCRIPT "$@"
+RC="$?"
+if [ "$RC" -ne 0 ]; then
+  echo "ERROR: $SCRIPT failed."
+  exit "$RC"
 fi
 exit 0
 
