firmware: use shar to replace tar+gz, for better AU delta generation
The firmware updater was using tar+gz to create an archive bundle for firmware
image, supporting programs and scripts. However time stamps and compression in
tar+gz caused OS AU delta generation to have problem creating minimized diff
output.

This CL replaced tar+gz with "shar" so that changes in each individual file
won't affect other files (especially that the largest blob, main firmware image,
usually don't change).

Compare "bsdiff" result for two builds without changing contents in firmware
updater:
 - Before this CL, diff size = 1905142 bytes
 - After this CL, diff size = 255 bytes

BUG=chromium-os:20027
TEST=emrege-x86-zgb chromeos-firmware-zgb
     ./chromeos-firmware --sb_extract . # see files extracted in place
     ./chromeos-firmware --sb_repack /tmp/xxx # files in bundle updated
     ./chromeos-firmware --mode=recovery # works as normal

Change-Id: I3a4c8f0c636c0c4f22eede59911039c4b7c46994
Reviewed-on: http://gerrit.chromium.org/gerrit/7310
Reviewed-by: Randall Spangler <rspangler@chromium.org>
Tested-by: Hung-Te Lin <hungte@chromium.org>

diff --git a/pack_stub b/pack_stub
--- a/pack_stub
+++ b/pack_stub
@@ -12,171 +12,220 @@ TARGET_SCRIPT="REPLACE_SCRIPT"
 
 # Export all version information
 export TARGET_FWID TARGET_ECID TARGET_PLATFORM TARGET_UNSTABLE TARGET_SCRIPT
-
-# All scripts should die on error unless commands are specifically excepted
-# by prefixing with '!' or surrounded by 'set +e' / 'set -e'.
 set -e
-# Clean up on regular or error exits.
-trap clean_temp EXIT
 
 # Global variables
-ORIGINAL_PARAMS="$@"
+SELF="$(readlink -f "$0")"
 
 # Set by make_temp function and removed by clean_temp
 TMP_DIR=
-# Set by allow_temp_exec and will invoke unmount in clean_temp
-IS_NEED_UMOUNT=
-# Decides if we need to print verbose messages
-IS_VERBOSE=
-# The default script to be invoked from extracted resource
+# Decides if we need to print debug messages
+IS_DEBUG=
+# The default script to be invoked from extracted bundle
 SCRIPT="./${TARGET_SCRIPT:-updater.sh}"
 
-IGNORE_TAG_FILE='/root/.leave_firmware_alone'
-force_flag=""
+# Tag file to prohibit updater execution
+TAG_FILE_DISABLED='/root/.leave_firmware_alone'
+# Set to True to bypass checking TAG_FILE_DISABLED
+IS_FORCED=
 
+# Set to true to prevent printing error alerts by error return value
+IS_IGNORE_RC=
 
-# Prints a message and return an error code.
-error_exit() {
-  echo $1
-  exit 1
+# Prints a message and return an error code ($1).
+die_as() {
+  local ret="$1"
+  shift
+  echo "ERROR: $@" >&2
+  exit "$ret"
 }
 
-# Prints messages if $IS_VERBOSE is not empty.
-verbose_message() {
-  if [ -n "$IS_VERBOSE" ]; then
-    echo "$*"
-  fi
+# Prints a message and return error as 1.
+die() {
+  die_as 1 "$@"
 }
 
-# Untar the file to a temp directory, then chdir to that directory.
-untar_and_chdir() {
-  SELF="$1"
-
-  verbose_message "Extract to $TMP_DIR ..."
-  uudecode -o - "$SELF" | tar -C "$TMP_DIR" -zxf -
-
-  if [ ! -x "$TMP_DIR" -o ! -d "$TMP_DIR" ]; then
-    error_exit "Create temp directory $TMP_DIR failed ..."
-  fi
-
-  if ! cd "$TMP_DIR"; then
-    error_exit "Cannot chdir to $TMP_DIR ..."
-  fi
+# Prints messages if $IS_DEBUG is not empty.
+debug() {
+  [ -z "$IS_DEBUG" ] || echo "$@" >&2
 }
 
+# Creates a temporary folder
 make_temp() {
-  TMP_DIR=$(mktemp -d)
+  TMP_DIR="$(mktemp -d --tmpdir)" ||
+    die "Failed to create temporary folder"
+  trap clean_temp EXIT
 }
 
-allow_temp_exec() {
-  if [ -z "$TMP_DIR" ]; then
-    error_exit "allow_temp_exec: Temp folder is empty."
-  fi
-  # TODO(hungte) check if we really need to re-mount tmp.
-  verbose_message "Bind mounting tmp path exec ..."
-  mount --bind "$TMP_DIR" "$TMP_DIR"
-  mount -o remount,exec "$TMP_DIR"
-  IS_NEED_UMOUNT=1
+# Creates a temporary folder with execution permission
+make_exec_temp() {
+  make_temp
+  debug "bind and remount for allowing execution ..."
+  mount --bind "$TMP_DIR" "$TMP_DIR" &&
+    mount -o remount,exec "$TMP_DIR" ||
+    die "Failed to enable execution permission of folder $TMP_DIR"
 }
 
+# Cleans temporary folders
 clean_temp() {
-  verbose_message "clean_temp is invoked."
-  if [ -z "$TMP_DIR" ]; then
-    return
+  debug "clean_temp: started."
+  if [ -d "$TMP_DIR" ]; then
+    umount -f "$TMP_DIR" >/dev/null 2>&1 || true
+    rm -rf "$TMP_DIR" >/dev/null 2>&1 || true
+    TMP_DIR=""
   fi
-  # Attempt to cd to OLDPWD
-  if ! cd - >/dev/null 2>&1; then
-    verbose_message "Failed to cd -. chdir'd to /"
-    cd /
-  fi
-  if [ -n "$IS_NEED_UMOUNT" ]; then
-    verbose_message "Unmount temporary folder $TMP_DIR..."
-    umount "$TMP_DIR"
-  fi
-  verbose_message "Clean up $TMP_DIR ..."
-  rm -rf "$TMP_DIR"
-  TMP_DIR=""
 }
 
-SELF="$0"
-RC=0
-IGNORE_RC=
+# Extracts bundle content to specified location
+extract_bundle() {
+  local destination="$1"
+  "$SELF" --sb_extract "$destination" >/dev/null ||
+    die "Cannot extract bundle content to: $destination"
+}
 
-case "$1" in
-  -V)
-    # Quick way to provide version information
-    uudecode -o - "$SELF" | tar zxO ./VERSION
-    exit 0
-    ;;
-  --sb_check)
+# Executes a script in bundle
+exec_bundle_script() {
+  local rc=0
+  make_exec_temp
+  extract_bundle "$TMP_DIR"
+  [ -x "$TMP_DIR/$SCRIPT" ] || die "Missing program in bundle: $SCRIPT"
+
+  debug "Start running script: $SCRIPT $@"
+  (cd "$TMP_DIR" && PATH="$TMP_DIR:$PATH" "$SCRIPT" "$@") || rc="$?"
+
+  if [ "$rc" -ne 0 -a -z "$IS_IGNORE_RC" ]; then
+    die_as "$rc" "Execution failed: $SCRIPT (error code = $rc)"
+  fi
+  exit "$rc"
+}
+
+# Prepares for extraction with shar
+prepare_shar_extract() {
+  local destination="$1"
+  if [ -z "$destination" ]; then
     make_temp
-    untar_and_chdir "$SELF"
-    md5sum -c VERSION || RC=$?
-    exit $RC
-    ;;
-  --sb_extract)
-    make_temp
-    echo "The resources are extracted into: $TMP_DIR"
-    untar_and_chdir "$SELF"
-    # Don't remove the temporary folder on exit.
+    destination="$TMP_DIR"
+    # Don't remove the temporary files
     TMP_DIR=""
-    exit 0
-    ;;
-  -h | "-?" | --help)
-    echo "
+  fi
+  cd "$destination" || die "Invalid destination: $destination"
+  exec >/dev/null  # Prevent shar messages in stdout
+  set -- "-c"  # Force shar to overwrite files
+}
+
+# Repacks current file ($SELF) by given source folder.
+perform_shar_repack() {
+  local new_source="$1"
+  local cut_mark="$(sed -n '/^##CUTHERE##/=' "$SELF")"
+  local md5_file="$new_source/VERSION.md5"
+
+  [ "$cut_mark" -gt 0 ] || die "File corrupted: $SELF"
+  sed -i "$((cut_mark + 1)),\$d" "$SELF" ||
+    die "Failed to truncate existing data in $SELF"
+
+  # Update checksum data for every files except VERSION*
+  (cd "$new_source" &&
+   echo "Package Content:" &&
+   md5sum -b ./* | grep -v ' ../VERSION') >"$md5_file"
+
+  # Build shar content
+  (cd "$new_source" &&
+   shar -Q -q -x -m -w -D --no-i18n -z -g 1 . |
+   sed -r 's/^lock_dir=_sh.*/lock_dir=_fwupdate/;
+           s"^begin ([0-9]+) _sh[^/]*"begin \1 _fwupdate"
+           /^# Made on .* by/d;
+           /^# Source directory was /d') >>"$SELF" ||
+   die "Failed repacking from $new_source"
+}
+
+# Prints the VAR from '--param VAR' and '--param=VAR' format.
+get_parameter_variable() {
+  local param="$1"
+  local param_name="${param%%=*}"
+  local param_value="${param#*=}"
+
+  if [ "$param" = "$param_name" ]; then
+    echo "$2"
+  else
+    echo "$param_value"
+  fi
+}
+
+# Main entry
+main() {
+  local original_params="$*"
+
+  case "$1" in
+    --sb_extract | --sb_extract=*)
+      local destination="$(get_parameter_variable "$@")"
+      echo "Extracting to: $destination"
+      prepare_shar_extract "$destination"
+      return  # Let shar handle the remaining stuff
+      ;;
+
+    --sb_repack )
+      local new_source="$(get_parameter_variable "$@")"
+      [ -d "$new_source" ] || die "Invalid source folder: $new_source"
+      echo "Repacking from: $new_source"
+      perform_shar_repack "$new_source"
+      exit 0
+      ;;
+
+    -V)
+      # Read information
+      make_temp
+      extract_bundle "$TMP_DIR"
+      cat "$TMP_DIR/VERSION"*
+      exit 0
+      ;;
+
+    -h | "-?" | --help)
+      echo "
 USAGE: $SELF [bundle_option|--] [updater_options]
 
 bundle_option (only one option can be selected):
   -h,--help:  Show usage help
   -V:  show version and content of bundle
-  --force:  force execution and ignore $IGNORE_TAG_FILE
-  --sb_check:  check bundle ingegrity
-  --sb_extract:  extract bundle content to a temporary folder
+  --force:  force execution and ignore $TAG_FILE_DISABLED
+  --sb_extract [PATH]:  extract bundle content to a temporary folder
+  --sb_repack PATH:  update bundle content from given folder
 
 updater_options:
-    "
-    # Invoke updater with -h for usage help
-    set -- "-h"
-    force_flag=1
-    IGNORE_RC=1
-    ;;
-  --force)
-    # Pass this into updaters
-    force_flag=1
-    ;;
-  --debug | --verbose | -v)
-    # do not shift here because this needs to be passed into the script
-    IS_VERBOSE=1
-    ;;
-  --)
-    shift
-    ;;
-esac
+      "
+      # Invoke script with -h for usage help
+      IS_IGNORE_RC=TRUE
+      exec_bundle_script "-h"
+      ;;
 
-# Do nothing if we're debugging BIOS changes, unless forced
-if [ -e "$IGNORE_TAG_FILE" ] && [ -z "${force_flag:-}" ]; then
-  echo "WARNING: $0 is disabled by $IGNORE_TAG_FILE"
-  echo "To force execution, please prefix --force to your command:"
-  echo " sudo $0 --force $ORIGINAL_PARAMS"
-  exit 0
-fi
+    --force)
+      # Pass this into updaters
+      IS_FORCED=TRUE
+      ;;
 
-# Prepare execution environment
-make_temp
-allow_temp_exec
-untar_and_chdir "$SELF"
-if [ ! -x $SCRIPT ]; then
-  error_exit "Cannot execute $SCRIPT"
-fi
+    --debug | --debug | -v)
+      # do not shift here because this needs to be passed into the script
+      IS_DEBUG=TRUE
+      ;;
 
-# Are we running in legacy mode or new flavor?
-PATH=".:$PATH"
+    --)
+      shift
+      ;;
+  esac
 
-verbose_message "Run built-in script ($SCRIPT) ..."
-$SCRIPT "$@" || RC="$?"
-if [ "$RC" -ne 0 -a -z "$IGNORE_RC" ]; then
-  echo "ERROR: $SCRIPT failed."
-fi
-exit $RC
+  # Do nothing if the OS specifies that.
+  # TODO(hungte) move this flag to kernel command line, or updater bundle
+  # itself.
+  if [ -e "$TAG_FILE_DISABLED" ] && [ -z "$IS_FORCED" ]; then
+    echo "WARNING: $SELF is disabled by $TAG_FILE_DISABLED"
+    echo "To force execution, please prefix --force to your command:"
+    echo " sudo $SELF --force $original_params"
+    exit 0
+  fi
 
-# Below are uuencoded blob. Don't put code behind exit 0.
+  exec_bundle_script "$@"
+}
+
+main "$@"
+
+# Below are for shar execution. Don't put any code below main.
+##CUTHERE##################################################################
